##
## LKL platform registration
##
$(eval $(call addplat_s,lkl,$(CONFIG_PLAT_LKL)))

##
## LKL platform library registration
##
$(eval $(call addplatlib,lkl,liblklplat))

##
## Platform library definitions
##
